name: github-release

on:
  workflow_dispatch:
    inputs:
      build_meta:
        description: 'Build meta to use as source'
        required: true
      mvn_version:
        description: 'Maven version to use'
        required: true

permissions:
  contents: write
  packages: write

jobs:
  github-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Update README.md
        run: |
          chmod +x update_readme.sh
          ./update_readme.sh ${{ github.event.inputs.build_meta }} ${{ github.event.inputs.mvn_version }}
      - name: Generate release info
        run: |
          cd scripts
          chmod +x create_release_info.sh
          ./create_release_info.sh ${{ github.event.inputs.build_meta }} https://github.com/${{github.repository}}/actions/runs/${{github.run_id}} ${{github.run_number}} ${{ github.event.inputs.mvn_version }}
      - name: Create Release
        run: |
          gh release create ${{env.release_tag_name}} --title "${{env.release_name}}" --notes-file release_info/release_message.md
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add build_meta.json
        run: |
          gh release upload ${{env.release_tag_name}} release_info/build_meta.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create artifacts
        run: chmod +x generate_artifacts.sh && ./generate_artifacts.sh ${{ github.event.inputs.build_meta }} ${{ github.event.inputs.mvn_version }}
      - name: Upload artifacts to GitHub release
        run: |
          cd out
          gh release upload ${{env.release_tag_name}} $(find . -type f -name "*.jar" -printf "%p ")
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Java for publishing to GitHub Packages
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish to GitHub Packages
        run: chmod +x upload_artifacts.sh && ./upload_artifacts.sh ${{ github.event.inputs.build_meta }} https://maven.pkg.github.com/${{ github.repository }} github ${{ github.event.inputs.mvn_version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
